-- =============================================================================
-- V1__initial_schema.sql
-- Simple Control PDKS — İlk şema
-- Hibernate CamelCaseToUnderscoresNamingStrategy çıktısıyla birebir eşleşir.
-- pg_dump v17.4 çıktısından elde edilmiştir.
-- =============================================================================

-- ─── deleted_transaction_logs ────────────────────────────────────────────────
CREATE TABLE deleted_transaction_logs (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted_at              timestamp(6) WITHOUT TIME ZONE NOT NULL,
    deleted_by              varchar(255)                   NOT NULL,
    latitude                double precision               NOT NULL,
    longitude               double precision               NOT NULL,
    method                  varchar(255)                   NOT NULL,
    original_transaction_id bigint                         NOT NULL,
    reason                  varchar(1000)                  NOT NULL,
    "timestamp"             timestamp(6) WITHOUT TIME ZONE NOT NULL,
    type                    varchar(255)                   NOT NULL,
    username                varchar(255)                   NOT NULL,
    CONSTRAINT deleted_transaction_logs_method_check
        CHECK (method IN ('QR', 'GPS', 'MANUAL')),
    CONSTRAINT deleted_transaction_logs_type_check
        CHECK (type IN ('GIRIS', 'CIKIS'))
);

-- ─── shifts ──────────────────────────────────────────────────────────────────
CREATE TABLE shifts (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active                 boolean       NOT NULL,
    break_minutes          integer       NOT NULL,
    end_time               time(0)       NOT NULL,
    firm_id                varchar(50)   NOT NULL,
    late_tolerance_minutes integer       NOT NULL,
    name                   varchar(100)  NOT NULL,
    start_time             time(0)       NOT NULL
);

-- ─── users ───────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active               boolean        NOT NULL,
    created_at           timestamp(6)   WITHOUT TIME ZONE NOT NULL,
    firm_id              varchar(50)    NOT NULL,
    full_name            varchar(150),
    must_change_password boolean        NOT NULL,
    password             varchar(255)   NOT NULL,
    role                 varchar(20)    NOT NULL,
    username             varchar(100)   NOT NULL,
    shift_id             bigint,
    CONSTRAINT users_role_check
        CHECK (role IN ('EMPLOYEE', 'ADMIN')),
    CONSTRAINT fk_users_shift
        FOREIGN KEY (shift_id) REFERENCES shifts (id)
);

-- ─── devices ─────────────────────────────────────────────────────────────────
CREATE TABLE devices (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active        boolean        NOT NULL,
    device_id     varchar(100)   NOT NULL,
    device_name   varchar(100),
    registered_at timestamp(6)   WITHOUT TIME ZONE NOT NULL,
    user_id       bigint         NOT NULL,
    CONSTRAINT uq_devices_device_id UNIQUE (device_id),
    CONSTRAINT uq_devices_user_id   UNIQUE (user_id),
    CONSTRAINT fk_devices_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ─── locations ───────────────────────────────────────────────────────────────
CREATE TABLE locations (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active        boolean          NOT NULL,
    code          varchar(255)     NOT NULL,
    firm_id       varchar(50)      NOT NULL,
    latitude      double precision NOT NULL,
    longitude     double precision NOT NULL,
    name          varchar(255),
    radius_meters integer          NOT NULL,
    CONSTRAINT uq_locations_firm_code UNIQUE (firm_id, code)
);

-- ─── suspicious_attempts ─────────────────────────────────────────────────────
CREATE TABLE suspicious_attempts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   varchar(255)                   NOT NULL,
    latitude    double precision               NOT NULL,
    longitude   double precision               NOT NULL,
    reason      varchar(255)                   NOT NULL,
    "timestamp" timestamp(6) WITHOUT TIME ZONE NOT NULL,
    user_id     bigint                         NOT NULL,
    CONSTRAINT suspicious_attempts_reason_check
        CHECK (reason IN ('GEOFENCE_VIOLATION', 'IMPOSSIBLE_SPEED', 'FROZEN_COORDINATE', 'MOCK_FLAG')),
    CONSTRAINT fk_suspicious_attempts_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ─── transactions ────────────────────────────────────────────────────────────
CREATE TABLE transactions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamp(6)                   WITHOUT TIME ZONE NOT NULL,
    device_id   varchar(255)                   NOT NULL,
    latitude    double precision               NOT NULL,
    longitude   double precision               NOT NULL,
    manual      boolean                        NOT NULL,
    manual_note varchar(500),
    method      varchar(255)                   NOT NULL,
    qr_content  varchar(255),
    "timestamp" timestamp(6)                   WITHOUT TIME ZONE NOT NULL,
    type        varchar(255)                   NOT NULL,
    location_id bigint,
    user_id     bigint                         NOT NULL,
    CONSTRAINT transactions_method_check
        CHECK (method IN ('QR', 'GPS', 'MANUAL')),
    CONSTRAINT transactions_type_check
        CHECK (type IN ('GIRIS', 'CIKIS')),
    CONSTRAINT fk_transactions_location
        FOREIGN KEY (location_id) REFERENCES locations (id),
    CONSTRAINT fk_transactions_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);
