-- =============================================================================
-- V2__split_users_and_employees.sql
-- users tablosundan personel bilgisi ayrıştırılıyor:
--   - kimlik/giriş bilgisi users'ta kalıyor
--   - ad/soyad/kart bilgisi yeni employees tablosuna taşınıyor
-- =============================================================================

-- ─── employees ───────────────────────────────────────────────────────────────
CREATE TABLE employees (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firm_id    varchar(50)                    NOT NULL,
    first_name varchar(75)                    NOT NULL,
    last_name  varchar(75)                    NOT NULL,
    card_no    varchar(50)                    NOT NULL,
    active     boolean                        NOT NULL,
    created_at timestamp(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uq_employees_firm_card UNIQUE (firm_id, card_no)
);

-- ─── users tablosunu güncelle ─────────────────────────────────────────────────
ALTER TABLE users
    ADD COLUMN  employee_id bigint,
    ADD CONSTRAINT uq_users_employee UNIQUE (employee_id),
    ADD CONSTRAINT fk_users_employee FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE users
    DROP COLUMN full_name;
