-- =============================================================================
-- V4__work_groups_and_holidays.sql
-- Faz 2: Calisma Grubu, Vardiyalarin genisletilmesi ve Tatil modeli
-- =============================================================================

-- 1. Vardiyalara (shifts) erken cikis toleransi ekle
ALTER TABLE shifts
    ADD COLUMN early_exit_tolerance_minutes integer NOT NULL DEFAULT 0;

-- 2. Calisma Gruplari (work_groups)
CREATE TABLE work_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firm_id varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    daily_work_minutes integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uq_work_groups_firm_name_active
    ON work_groups (firm_id, name)
    WHERE active = true;

-- 3. Calisma Grubu Gunleri (work_group_days)
CREATE TABLE work_group_days (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_group_id bigint NOT NULL,
    day_of_week integer NOT NULL,
    shift_id bigint,
    
    CONSTRAINT fk_work_group_days_work_group
        FOREIGN KEY (work_group_id)
        REFERENCES work_groups (id)
        ON DELETE CASCADE,
        
    CONSTRAINT fk_work_group_days_shift
        FOREIGN KEY (shift_id)
        REFERENCES shifts (id),
        
    CONSTRAINT uq_work_group_days_group_day
        UNIQUE (work_group_id, day_of_week),
        
    CONSTRAINT chk_work_group_days_day_of_week
        CHECK (day_of_week BETWEEN 1 AND 7)
);

-- 4. Tatiller (holidays)
CREATE TABLE holidays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firm_id varchar(50) NOT NULL,
    holiday_date date NOT NULL,
    name varchar(100) NOT NULL,
    
    CONSTRAINT uq_holidays_firm_date
        UNIQUE (firm_id, holiday_date)
);

-- 5. Personellere calisma grubu baglantisi (employees tablosuna)
ALTER TABLE employees
    ADD COLUMN work_group_id bigint,
    ADD CONSTRAINT fk_employees_work_group
        FOREIGN KEY (work_group_id)
        REFERENCES work_groups (id);
