CREATE TABLE raw_scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    device_id VARCHAR(100) NOT NULL,
    scanned_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    mock_location BOOLEAN NOT NULL,
    location_id BIGINT,
    method VARCHAR(20) NOT NULL CHECK (method IN ('QR', 'GPS', 'MANUAL')),
    qr_content VARCHAR(255),
    suspicious BOOLEAN NOT NULL DEFAULT false,
    suspicious_reason VARCHAR(50) CHECK (suspicious_reason IN ('GEOFENCE_VIOLATION', 'IMPOSSIBLE_SPEED', 'FROZEN_COORDINATE', 'MOCK_FLAG')),
    client_id VARCHAR(100),
    manual_note VARCHAR(500),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_raw_scans_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_raw_scans_location FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE UNIQUE INDEX uq_raw_scans_client_id ON raw_scans (client_id) WHERE client_id IS NOT NULL;
CREATE INDEX idx_raw_scans_employee_scanned_at ON raw_scans (employee_id, scanned_at);
