CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firm_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uq_departments_firm_name_active 
ON departments (firm_id, name) 
WHERE active = true;

ALTER TABLE employees
ADD COLUMN department_id BIGINT;

ALTER TABLE employees
ADD CONSTRAINT fk_employees_department
FOREIGN KEY (department_id) REFERENCES departments (id);
